//created on: jun 19, 2017
package com.grupo4.drools.rules

import com.grupo4.inversiones.entidades.Empresa;
import java.util.Calendar;
import java.util.List;
import java.util.Collections;

global java.util.List listaEmpresas;
global java.lang.Integer anio;

rule "Longevidad"
dialect "java"
    //include attributes such as "salience" here...
    when
    $e: Empresa(inicioActividad < (anio - 10))
    then
		listaEmpresas.add($e);
		//Collections.sort(listaEmpresas,((a,b) -> a.getInicioActividad().compareTo(b.getInicioActividad())));
	end

/*rule "Maximizar ROE"

    when
        //conditions
    then
        //actions

end

rule "Minimizar el nivel de deuda"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end

rule "Márgenes consistentemente crecientes"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end */
